# <span style='color:black'> <center>Unión de datos con Pandas</center> </span>
## 2. Diferentes tipos de joins
<p><img src="https://cdn.prgloo.com/media/13f61baf042143dca612098e751cfa07.png?width=1024&height=960" width="750"</p>

<p><img src="https://learnsql.es/blog/como-aprender-a-hacer-joins-en-sql/2.png" width="550"</p>

## Left join
<p>Un <b>left join</b> devuelve todas las filas de la tabla de la izquierda, y las filas coincidentes de la tabla de la derecha.

En el siguiente ejercicio la tabla de <code>movies</code> es propocionada por voluntarios que salen al mundo, recopilan datos e ingresan en la base de datos. Esto incluye datos financieros, como el presupuesto y los ingresos de la película. Si desean saber a qué películas todavía les faltan datos, puedes usar un <code>left join</code> para identificarlas uniendola con la tabla de <code>financials</code>.</p>

In [1]:
# Importar pandas y matplotlib.pyplot
import pandas as pd
import matplotlib.pyplot as plt
# Importar datasets
movies = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\movies.p"
)
financials = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\financials.p"
)

In [2]:
print(movies.head(5))
print(financials.head(5))

      id                 title  popularity release_date
0    257          Oliver Twist   20.415572   2005-09-23
1  14290  Better Luck Tomorrow    3.877036   2002-01-12
2  38365             Grown Ups   38.864027   2010-06-24
3   9672              Infamous    3.680896   2006-11-16
4  12819       Alpha and Omega   12.300789   2010-09-17
       id     budget       revenue
0   19995  237000000  2.787965e+09
1     285  300000000  9.610000e+08
2  206647  245000000  8.806746e+08
3   49026  250000000  1.084939e+09
4   49529  260000000  2.841391e+08

In [3]:
from IPython.display import display

In [4]:
# Une la tabla de movies con la de financials usando un left join
movies_financial = movies.merge(financials, on='id', how= 'left')
display(movies_financial)
# Contar el número de filas que faltan en la columna de 'budget'
filtro =movies_financial['budget'].isnull()
movies_financial[filtro]
movies_financial[filtro].count()
# Imprime el resultado

,id,title,popularity,release_date,budget,revenue
0,257,Oliver Twist,20.415572,2005-09-23,50000000.0,42093706.0
1,14290,Better Luck Tomorrow,3.877036,2002-01-12,NaN,NaN
2,38365,Grown Ups,38.864027,2010-06-24,80000000.0,271430189.0
3,9672,Infamous,3.680896,2006-11-16,13000000.0,1151330.0
4,12819,Alpha and Omega,12.300789,2010-09-17,20000000.0,39300000.0
...,...,...,...,...,...,...
4798,3089,Red River,5.344815,1948-08-26,3000000.0,9012000.0
4799,11934,The Hudsucker Proxy,14.188982,1994-03-11,NaN,NaN
4800,13807,Exiled,8.486390,2006-09-06,NaN,NaN
4801,73873,Albert Nobbs,7.802245,2011-12-21,8000000.0,5634828.0
4802,11622,Blast from the Past,8.737058,1999-02-12,35000000.0,40263020.0

id              1574
title           1574
popularity      1574
release_date    1573
budget             0
revenue            0
dtype: int64

## Left join vs Inner join
<p><code>.merge(table, how="left")</code> es una técnica útil para enriquecer o mejorar un conjunto de datos con información adicional de una tabla diferente. En este ejercicio, comenzaras tu objetivo es enriquecer estos datos agregando la línea de etiqueta de marketing para cada película. Compararás los resultados de un <b>left join</b> y un <b>inner join</b>. 

Seguirás usando la tabla <code>movies</code> y tendrás que carga la tabla de <code>taglines</code></p>

In [5]:
# Importar datasets
taglines = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\taglines.p"
)

In [6]:
display(taglines.head())

       id                                         tagline
0   19995                     Enter the World of Pandora.
1     285  At the end of the world, the adventure begins.
2  206647                           A Plan No One Escapes
3   49026                                 The Legend Ends
4   49529            Lost in our world, found in another.

In [7]:
tabla= movies.merge(taglines,on='id',how='left')
display(tabla.head())

,id,title,popularity,release_date,tagline
0,257,Oliver Twist,20.415572,2005-09-23,NaN
1,14290,Better Luck Tomorrow,3.877036,2002-01-12,Never underestimate an overachiever.
2,38365,Grown Ups,38.864027,2010-06-24,Boys will be boys. . . some longer than others.
3,9672,Infamous,3.680896,2006-11-16,There's more to the story than you know
4,12819,Alpha and Omega,12.300789,2010-09-17,A Pawsome 3D Adventure

In [8]:
# Une la tabla movies con la tabla taglines con un left join


# Imprime la dimensión de la tabla
print(tabla.shape)
print(movies.shape)

(4803, 5)
(4803, 4)

In [9]:
# Une la tabla movies con la tabla taglines con un inner join join
tabla2= movies.merge(taglines, on='id', how='inner')
display(tabla2)
# Imprime la dimensión de la tabla
print(tabla2.shape)

,id,title,popularity,release_date,tagline
0,14290,Better Luck Tomorrow,3.877036,2002-01-12,Never underestimate an overachiever.
1,38365,Grown Ups,38.864027,2010-06-24,Boys will be boys. . . some longer than others.
2,9672,Infamous,3.680896,2006-11-16,There's more to the story than you know
3,12819,Alpha and Omega,12.300789,2010-09-17,A Pawsome 3D Adventure
4,49529,John Carter,43.926995,2012-03-07,"Lost in our world, found in another."
...,...,...,...,...,...
3950,12281,Mean Creek,8.519202,2004-01-15,"Beneath the surface, everyone has a secret."
3951,3089,Red River,5.344815,1948-08-26,Big as the men who faced this challenge! Bold ...
3952,11934,The Hudsucker Proxy,14.188982,1994-03-11,They took him for a fall guy... but he threw t...
3953,73873,Albert Nobbs,7.802245,2011-12-21,A man with a secret. A woman with a dream.
3954,11622,Blast from the Past,8.737058,1999-02-12,She'd never met anyone like him. He's never me...

(3955, 5)

## Right join
<p>Un <b>right join</b> devuelve todas las filas de la tabla de la derecha, y las filas coincidentes de la tabla de la izquierda

En el siguiente ejercicio contestaremos la siguiente pregunta: ¿Cuáles son los géneros de las películas más populares? Para responder a esta pregunta, debes unir los datos de las tablas de <code>movies</code> y <code>movie_to_genres</code>. Para asegurarse de que está analizando todas las películas utiliza el tipo de join correcto. Para completar tu análisis, cuenta el número de géneros diferentes. Además, las dos tablas se pueden combinar por el ID de la película. Sin embargo, en la tabla <code>movies</code> esa columna se llama <code>id</code>, y en la tabla <code>movies_to_genres</code> se llama <code>movie_id</code>.
</p>

In [10]:
# Importar datasets
movie_to_genres = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\movie_to_genres.p"
)

In [11]:
display(movie_to_genres.columns.tolist())
display(movies.columns.tolist())

['movie_id', 'genre']

['id', 'title', 'popularity', 'release_date']

In [12]:
# Usa right join para unir la tabla movie_to_genres con movies
tabla3= movie_to_genres.merge(movies, left_on= 'movie_id',right_on='id', how= 'right')
display(tabla3.head())
# Cuenta el número de generos, columna 'genre'
tabla3['genre'].value_counts()
# Muestra el resultado en una gráfica de barras

   movie_id   genre     id                 title  popularity release_date
0     257.0   Crime    257          Oliver Twist   20.415572   2005-09-23
1     257.0   Drama    257          Oliver Twist   20.415572   2005-09-23
2     257.0  Family    257          Oliver Twist   20.415572   2005-09-23
3   14290.0   Crime  14290  Better Luck Tomorrow    3.877036   2002-01-12
4   14290.0   Drama  14290  Better Luck Tomorrow    3.877036   2002-01-12

genre
Drama              2297
Comedy             1722
Thriller           1274
Action             1154
Romance             894
Adventure           790
Crime               696
Science Fiction     535
Horror              519
Family              513
Fantasy             424
Mystery             348
Animation           234
History             197
Music               185
War                 144
Documentary         110
Western              82
Foreign              34
TV Movie              8
Name: count, dtype: int64

## Outer join
<p>Un aspecto interesante de usar un <b>outer join</b> es que, debido a que devuelve todas las filas de las tablas combinadas y nulas donde no coinciden, puedes usarla para buscar filas que no tienen una coincidencia en la otra tabla. Para ver su funcionalidad, vamos a utilizar los datos de una lista de actores de dos películas populares: Iron Man 1 y Iron Man 2. La mayoría de los actores interpretaron a ambas películas. Utiliza un <code>outer join</code> para encontrar actores que no actuaron en ambas películas</p>
<p>
<img src=https://files.realpython.com/media/join_diagram.93e6ef63afbe.png width="350">
</p>

In [85]:
# Importar datasets
# Importar dataset

In [13]:
Iron_man_1 = pd.read_excel(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\iron_man_actors.xlsx",
    sheet_name="Sheet1"
)
display(Iron_man_1.head())
Iron_man_2 = pd.read_excel(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\iron_man_actors.xlsx",
    sheet_name="Sheet2"
)
display(Iron_man_2.head())

                     character     id               name
0        Tony Stark / Iron Man   3223  Robert Downey Jr.
1                  War Machine  18288    Terrence Howard
2  Obadiah Stane / Iron Monger   1229       Jeff Bridges
3                       Yinsen  17857         Shaun Toub
4      Virginia "Pepper" Potts  12052    Gwyneth Paltrow

                                          character     id                name
0                             Tony Stark / Iron Man   3223   Robert Downey Jr.
1                           Virginia "Pepper" Potts  12052     Gwyneth Paltrow
2      Lt. Col. James "Rhodey" Rhodes / War Machine   1896         Don Cheadle
3  Natalie Rushman / Natasha Romanoff / Black Widow   1245  Scarlett Johansson
4                             Ivan Vanko / Whiplash   2295       Mickey Rourke

In [14]:
print(Iron_man_1.shape)
print(Iron_man_2.shape)

(87, 3)
(113, 3)

In [ ]:
# Une la tabla iron_man_1 con la tabla iron_man_2, no olvides usar sufijos ('_1', '_2')

# Crea una condición que devuelva verdadero si name_1 o name_2 son nulos

# Imprime los actores que no actuaron en ambas peliculas (Utiliza el indice creado previamente)
#iron_man[my_filter]